# Generated by Django 5.1.7 on 2025-04-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        default="Unknown", max_length=100, verbose_name="Brand"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        default="Unknown", max_length=100, verbose_name="Model"
                    ),
                ),
                ("year", models.IntegerField(default=2000, verbose_name="Year")),
                (
                    "license_plate",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="License Plate"
                    ),
                ),
                (
                    "vin",
                    models.CharField(
                        default="Unknown",
                        max_length=17,
                        unique=True,
                        verbose_name="VIN",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="White", max_length=50, verbose_name="Color"
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("DIESEL", "Diesel"),
                            ("PETROL", "Petrol"),
                            ("HYBRID", "Hybrid"),
                            ("ELECTRIC", "Electric"),
                        ],
                        default="DIESEL",
                        max_length=20,
                        verbose_name="Fuel Type",
                    ),
                ),
                (
                    "transmission",
                    models.CharField(
                        choices=[("MANUAL", "Manual"), ("AUTOMATIC", "Automatic")],
                        default="AUTOMATIC",
                        max_length=20,
                        verbose_name="Transmission",
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("TRUCK", "Truck"),
                            ("VAN", "Van"),
                            ("SUV", "SUV"),
                            ("PICKUP", "Pickup"),
                        ],
                        default="TRUCK",
                        max_length=20,
                        verbose_name="Vehicle Type",
                    ),
                ),
                ("mileage", models.IntegerField(default=0, verbose_name="Mileage")),
                (
                    "last_service_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Last Service Date"
                    ),
                ),
                (
                    "next_service_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Next Service Date"
                    ),
                ),
                (
                    "insurance_expiry",
                    models.DateField(
                        blank=True, null=True, verbose_name="Insurance Expiry Date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("IN_USE", "In Use"),
                            ("MAINTENANCE", "In Maintenance"),
                            ("OUT_OF_SERVICE", "Out of Service"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
