# Generated by Django 5.0.1 on 2026-02-20 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "0002_auto_20250602_1503"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("IMAGE", "Image"),
                            ("VIDEO", "Video"),
                            ("SOUND", "Sound"),
                        ],
                        max_length=10,
                        verbose_name="Media Type",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="vehicle_media/", verbose_name="File"),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=255, verbose_name="Title"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="vehicles.vehicle",
                        verbose_name="Vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle Media",
                "verbose_name_plural": "Vehicle Media Gallery",
                "ordering": ["-created_at"],
            },
        ),
    ]
