# Generated by Django 5.0.1 on 2026-02-18 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_alter_customuser_emergency_contact_and_more"),
        ("emergency", "0001_initial"),
        ("vehicles", "0002_auto_20250602_1503"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="emergencyincident",
            name="attachment",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="emergency/incidents/",
                verbose_name="Attachment",
            ),
        ),
        migrations.AddField(
            model_name="emergencyincident",
            name="video_attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="emergency/videos/",
                verbose_name="Video Attachment",
            ),
        ),
        migrations.AddField(
            model_name="emergencyresponse",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="emergency/responses/",
                verbose_name="Response Attachment",
            ),
        ),
        migrations.AlterField(
            model_name="emergencycontact",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="emergencycontact",
            name="phone_number",
            field=models.CharField(max_length=15, verbose_name="Phone Number"),
        ),
        migrations.AlterField(
            model_name="emergencycontact",
            name="relationship",
            field=models.CharField(max_length=50, verbose_name="Relationship"),
        ),
        migrations.AlterField(
            model_name="emergencycontact",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emergency_contact_list",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="emergencyincident",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="emergencyincident",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="emergency_incidents",
                to="accounts.driver",
                verbose_name="Driver",
            ),
        ),
        migrations.AlterField(
            model_name="emergencyincident",
            name="emergency_type",
            field=models.CharField(
                choices=[
                    ("ACCIDENT", "Accident"),
                    ("BREAKDOWN", "Breakdown"),
                    ("MEDICAL", "Medical Emergency"),
                    ("THEFT", "Theft"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=20,
                verbose_name="Emergency Type",
            ),
        ),
        migrations.AlterField(
            model_name="emergencyincident",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Latitude",
            ),
        ),
        migrations.AlterField(
            model_name="emergencyincident",
            name="location",
            field=models.CharField(max_length=255, verbose_name="Location"),
        ),
        migrations.AlterField(
            model_name="emergencyincident",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Longitude",
            ),
        ),
        migrations.AlterField(
            model_name="emergencyincident",
            name="reported_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reported_incidents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Reported By",
            ),
        ),
        migrations.AlterField(
            model_name="emergencyincident",
            name="reported_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Reported Time"),
        ),
        migrations.AlterField(
            model_name="emergencyincident",
            name="resolved_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Resolved Time"
            ),
        ),
        migrations.AlterField(
            model_name="emergencyincident",
            name="status",
            field=models.CharField(
                choices=[
                    ("REPORTED", "Reported"),
                    ("RESPONDING", "Responding"),
                    ("RESOLVED", "Resolved"),
                    ("CLOSED", "Closed"),
                ],
                default="REPORTED",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="emergencyincident",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emergency_incidents",
                to="vehicles.vehicle",
                verbose_name="Vehicle",
            ),
        ),
        migrations.AlterField(
            model_name="emergencyresponse",
            name="action_taken",
            field=models.TextField(blank=True, null=True, verbose_name="Action Taken"),
        ),
        migrations.AlterField(
            model_name="emergencyresponse",
            name="incident",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="emergency.emergencyincident",
                verbose_name="Incident",
            ),
        ),
        migrations.AlterField(
            model_name="emergencyresponse",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="emergencyresponse",
            name="responder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="emergency_responses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responder",
            ),
        ),
        migrations.AlterField(
            model_name="emergencyresponse",
            name="response_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Response Time"),
        ),
    ]
