# Generated by Django 5.0.1 on 2026-02-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emergency", "0002_emergencyincident_attachment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emergencyincident",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="emergencyincident",
            name="location",
            field=models.CharField(blank=True, max_length=255, verbose_name="Location"),
        ),
    ]
