# Generated by Django 5.1.7 on 2025-04-15 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_userrole_driver_emergencycontact_customuser_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emergencycontact",
            name="driver",
        ),
        migrations.AddField(
            model_name="customuser",
            name="emergency_contact",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="userrole",
            name="permissions",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.userrole",
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name="Driver",
        ),
        migrations.DeleteModel(
            name="EmergencyContact",
        ),
    ]
