# Generated by Django 5.1.7 on 2025-04-16 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_emergencycontact_driver_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="accounts.userrole",
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="name",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("coordinator", "Coordinator"),
                    ("driver", "Driver"),
                    ("testuser", "Test User"),
                ],
                max_length=32,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="permissions",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
