# Generated by Django 5.1.7 on 2025-04-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_customuser_role_alter_userrole_description_and_more"),
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("driver_license_number", models.CharField(max_length=50, unique=True)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "assigned_vehicles",
                    models.ManyToManyField(
                        blank=True, related_name="drivers", to="vehicles.vehicle"
                    ),
                ),
            ],
        ),
    ]
