# Generated by Django 5.1.7 on 2025-04-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_driver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrole",
            name="name",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("coordinator", "Coordinator"),
                    ("driver", "Driver"),
                    ("testuser", "Test User"),
                    ("maintenance_staff", "Maintenance Staff"),
                ],
                max_length=32,
                unique=True,
            ),
        ),
    ]
