# Generated by assistant: add status field to Driver to avoid NOT NULL failures in tests
from django.db import migrations, models


def set_default_status(apps, schema_editor):
    Driver = apps.get_model('accounts', 'Driver')
    for d in Driver.objects.all():
        d.status = 'active'
        d.save(update_fields=['status'])


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0008_remove_userrole_name_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='status',
            field=models.CharField(max_length=20, choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active'),
            preserve_default=False,
        ),
        migrations.RunPython(set_default_status, migrations.RunPython.noop),
    ]
