# Generated by Django 5.0.1 on 2026-02-18 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_add_driver_dates"),
        ("vehicles", "0002_auto_20250602_1503"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="emergency_contact",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Emergency Contact"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Phone Number"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="accounts.userrole",
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="assigned_vehicles",
            field=models.ManyToManyField(
                blank=True,
                related_name="drivers",
                to="vehicles.vehicle",
                verbose_name="Assigned Vehicles",
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="driver_license_number",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Driver License Number"
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="driver",
            name="first_name",
            field=models.CharField(max_length=50, verbose_name="First Name"),
        ),
        migrations.AlterField(
            model_name="driver",
            name="last_name",
            field=models.CharField(max_length=50, verbose_name="Last Name"),
        ),
        migrations.AlterField(
            model_name="driver",
            name="license_expiry_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="License Expiry Date"
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Phone Number"
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="name",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("coordinator", "Coordinator"),
                    ("driver", "Driver"),
                    ("testuser", "Test User"),
                    ("maintenance_staff", "Maintenance Staff"),
                ],
                max_length=32,
                verbose_name="Role Name",
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="permissions",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Permissions"
            ),
        ),
    ]
