# Generated by Django 5.1.7 on 2025-05-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emergency", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emergencyresponse",
            name="action_taken",
            field=models.TextField(blank=True, null=True),
        ),
    ]
