# Generated by Django 5.1.7 on 2025-05-20 19:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

"""Autogenerated migration."""

"""Migration file."""

class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0001_initial"),
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenance",
            name="completed_date",
            field=models.DateField(
                blank=True,
                help_text="Date the maintenance was completed.",
                null=True,
                verbose_name="Completed Date",
            ),
        ),
        migrations.AlterField(
            model_name="maintenance",
            name="cost",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Cost of the maintenance.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Maintenance Cost",
            ),
        ),
        migrations.AlterField(
            model_name="maintenance",
            name="description",
            field=models.TextField(
                help_text="Description of the maintenance work to be performed.",
                verbose_name="Maintenance Description",
            ),
        ),
        migrations.AlterField(
            model_name="maintenance",
            name="maintenance_type",
            field=models.CharField(
                choices=[
                    ("ROUTINE", "Routine Maintenance"),
                    ("REPAIR", "Repair"),
                    ("INSPECTION", "Inspection"),
                    ("OTHER", "Other"),
                ],
                default="ROUTINE",
                help_text="Type of maintenance (routine, repair, inspection, etc).",
                max_length=15,
                verbose_name="Maintenance Type",
            ),
        ),
        migrations.AlterField(
            model_name="maintenance",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Additional notes about the maintenance.",
                verbose_name="Additional Notes",
            ),
        ),
        migrations.AlterField(
            model_name="maintenance",
            name="odometer_reading",
            field=models.PositiveIntegerField(
                help_text="Odometer reading at the time of maintenance.",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Odometer Reading",
            ),
        ),
        migrations.AlterField(
            model_name="maintenance",
            name="scheduled_date",
            field=models.DateField(
                help_text="Date the maintenance is scheduled for.",
                verbose_name="Scheduled Date",
            ),
        ),
        migrations.AlterField(
            model_name="maintenance",
            name="service_provider",
            field=models.CharField(
                help_text="Provider performing the maintenance.",
                max_length=100,
                verbose_name="Service Provider",
            ),
        ),
        migrations.AlterField(
            model_name="maintenance",
            name="status",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Scheduled"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="SCHEDULED",
                help_text="Current status of the maintenance.",
                max_length=15,
                verbose_name="Maintenance Status",
            ),
        ),
        migrations.AlterField(
            model_name="maintenance",
            name="vehicle",
            field=models.ForeignKey(
                help_text="Vehicle associated with this maintenance record.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance_records",
                to="vehicles.vehicle",
                verbose_name="Vehicle",
            ),
        ),
    ]
